version: '3.8'

services:
  db:
    container_name : db-carpool
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: carpool
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -dcarpool -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migration/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
  api:
    container_name : api-carpool
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db :
        condition: service_healthy
volumes:
  pgdata:
