DROP TABLE IF EXISTS "schedule_passenger";
DROP TABLE IF EXISTS "schedule";
DROP TABLE IF EXISTS "car";
DROP TABLE IF EXISTS "user";
DROP TYPE IF EXISTS "country";
DROP TYPE IF EXISTS "category";
DROP TYPE IF EXISTS "user_role";